import json
datos={
    "tipo": "FACTURE",
    "n_factura": "Nº Facture",
    "serie": "Type",
    "fecha_factura": "Date Facture",
    "cod_cl": "Cod Cl",
    "cif_dni": "NºSiret",
    "alm": "Maga",
    "vendedor": "Vendeur",
    "ext_centralita": "PBX",
    "enviar_a":"Envoyer à:",
    "factura_a":"Facturer à:",
    "codigo":"Code Produit",
    "desc_art":"Désignation",
    "garantia":"Garantié",
    "ud":"Quantité",
    "precio":"Prix Ut",
    "dto":"%Reduct",
    "neto":"Net",
    "importes":"Montant HT",
    "importe":"Montant HT",
    "irpf":"%R.IRPF",
    "retencion":"Retencion",
    "transporte":"Transport",
    "imponible":"Base T.V.A",
    "por_iva":"%T.V.A",
    "iva":"T.V.A",
    "por_eqv":"%Eqv",
    "equivalencia":"",
    "t_factura":"Net à Payer",
    "pago":"Moyen de paiement:",
    "c_c":"C/C:",
    "p_realizados":"Paiements faits ou engrais appliqués:",
    "f_ven":"Date d´echéance",
    "importes2":"Net a Payer",
    "r_financiero":"Supplémet",
    "total":"Net à Payer €",
    "dat_banco":"Coordonnées bancaires",
    "swift":"Swift",
    "iban":"Iban",
    "c_c2":"C/C",
    "text1_atencion":'Attention, tout I´ article qui a les étiquettes de numéro de serie o garantie manipulées, enlevées ou end perdra la garantie.',
    "text2_atencion":'Pour faire effective  la garantie est indispensable envoyer avec I´ article la copie de la´achat, les manuels et les disques originals.',
    "fecha" :"Date",
    "recopilacion":"Encaissement",
    "admisible":"Recevable",
    "p_formulario":"Formularie de Paiement"
}
with open("cabecera_frances.json", "w") as archivo:
    # Convierte los datos en formato JSON y escribe en el archivo
    json.dump(datos, archivo)